### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [schafeld/picturefoods#47]
Hi... I am Chimzy, a Logo/Icon Designer... Came across your very interesting and cool project and I really like the idea behind the project and I want to propose a New Logo/Icon Design for your project. I will be doing this all for Free because of the Passion and Love i have to help contribute to amazing open Source Projects.

Working on the Logo Design idea Concept at the moment and I will share the concept here once I complete it, so you can share your feedback and also tell me any changes or tweaks you want.

Your response will be really appreciated...

Regards!

**Comment by schafeld** [comment]
Hi Chimzy,

thank you for the offer. Currently I intend to use this project (at least the UI/design part) as a personal portfolio. So I am at this moment not looking for any contribution on the design. I know there is still a long way to go for me regarding design/UI/UX of this project 🙈😅, but I want to show, that I can do code *and* design all by myself.

But you are of course free fork the repository and work on a design of your own. 

Kind regards,
Oliver

**Comment by chimzycash** [comment]
I appreciate your response... I am always available and you can notify me if you need a logo design for any open source project.
